log:
  filename: stderr
  # 0: trace, 1: debug, 2: info, 3: warn, 4: error, 5: critical, 6: off
  loglevel: 0
  pattern: "[%Y-%m-%d %H:%M:%S] [%L] [%P] [%T] %v"

sensors: [status, imu]

status:
  topic: /tinysk/status
  type: Status
  rate: 1

imu:
  topic: /tinysk/imu
  type: Imu
  rate: 100
  port: /dev/ttyUSB0
  baud_rate: 115200
